# Sample configuration
# Logging level for the application. One of debug, info, warn, or error
log-level: "info"
# Configuration for Prometheus metrics
metrics:
  # Whether to enable Prometheus metrics endpoint
  enabled: false
  # Address to serve Prometheus metrics on
  address: ":9100"
# Configuration for MMDVM clients (multiple DMR masters)
# mmdvm:
#   - name: ""
#     callsign: ""
#     radio-id: 0
#     rx-freq: 0
#     tx-freq: 0
#     tx-power: 0
#     color-code: 0
#     latitude: 0.0
#     longitude: 0.0
#     height: 0
#     location: ""
#     description: ""
#     url: ""
#     slots: 3
#     master-server: ""
#     password: "(secret)"
#     tg-rewrite:
#       - from-slot: 0
#         from-tg: 0
#         to-slot: 0
#         to-tg: 0
#         range: 1
#     pc-rewrite:
#       - from-slot: 0
#         from-id: 0
#         to-slot: 0
#         to-id: 0
#         range: 1
#     type-rewrite:
#       - from-slot: 0
#         from-tg: 0
#         to-slot: 0
#         to-id: 0
#         range: 1
#     src-rewrite:
#       - from-slot: 0
#         from-id: 0
#         to-slot: 0
#         to-id: 0
#         range: 1
#     pass-all-pc: []
#     pass-all-tg: []
# Configuration for the IPSC server
ipsc:
  # Interface to listen for IPSC packets on
  # interface: ""
  # Port to listen for IPSC packets on
  # port: 0
  # IP address to listen for IPSC packets on
  ip: "10.10.250.1"
  # Subnet mask for the virtual network interface created for IPSC packets
  subnet-mask: 24
  # Authentication configuration for the IPSC server
  auth:
    # Whether to require authentication for IPSC clients
    enabled: false
    # Authentication key for IPSC clients. Required if auth is enabled
    # key: "(secret)"
