// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"math"
	"slices"
	"strconv"
	"strings"
)

type metricsShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Address *string `json:"address" toml:"address" yaml:"address"`
}
type tGRewriteConfigShadow struct {
	FromSlot *uint `json:"from-slot" toml:"from-slot" yaml:"from-slot"`
	FromTG   *uint `json:"from-tg" toml:"from-tg" yaml:"from-tg"`
	ToSlot   *uint `json:"to-slot" toml:"to-slot" yaml:"to-slot"`
	ToTG     *uint `json:"to-tg" toml:"to-tg" yaml:"to-tg"`
	Range    *uint `json:"range" toml:"range" yaml:"range"`
}
type pCRewriteConfigShadow struct {
	FromSlot *uint `json:"from-slot" toml:"from-slot" yaml:"from-slot"`
	FromID   *uint `json:"from-id" toml:"from-id" yaml:"from-id"`
	ToSlot   *uint `json:"to-slot" toml:"to-slot" yaml:"to-slot"`
	ToID     *uint `json:"to-id" toml:"to-id" yaml:"to-id"`
	Range    *uint `json:"range" toml:"range" yaml:"range"`
}
type typeRewriteConfigShadow struct {
	FromSlot *uint `json:"from-slot" toml:"from-slot" yaml:"from-slot"`
	FromTG   *uint `json:"from-tg" toml:"from-tg" yaml:"from-tg"`
	ToSlot   *uint `json:"to-slot" toml:"to-slot" yaml:"to-slot"`
	ToID     *uint `json:"to-id" toml:"to-id" yaml:"to-id"`
	Range    *uint `json:"range" toml:"range" yaml:"range"`
}
type srcRewriteConfigShadow struct {
	FromSlot *uint `json:"from-slot" toml:"from-slot" yaml:"from-slot"`
	FromID   *uint `json:"from-id" toml:"from-id" yaml:"from-id"`
	ToSlot   *uint `json:"to-slot" toml:"to-slot" yaml:"to-slot"`
	ToID     *uint `json:"to-id" toml:"to-id" yaml:"to-id"`
	Range    *uint `json:"range" toml:"range" yaml:"range"`
}
type mMDVMShadow struct {
	Name         *string                    `json:"name" toml:"name" yaml:"name"`
	Callsign     *string                    `json:"callsign" toml:"callsign" yaml:"callsign"`
	ID           *uint32                    `json:"radio-id" toml:"radio-id" yaml:"radio-id"`
	RXFreq       *uint                      `json:"rx-freq" toml:"rx-freq" yaml:"rx-freq"`
	TXFreq       *uint                      `json:"tx-freq" toml:"tx-freq" yaml:"tx-freq"`
	TXPower      *uint8                     `json:"tx-power" toml:"tx-power" yaml:"tx-power"`
	ColorCode    *uint8                     `json:"color-code" toml:"color-code" yaml:"color-code"`
	Latitude     *float64                   `json:"latitude" toml:"latitude" yaml:"latitude"`
	Longitude    *float64                   `json:"longitude" toml:"longitude" yaml:"longitude"`
	Height       *uint16                    `json:"height" toml:"height" yaml:"height"`
	Location     *string                    `json:"location" toml:"location" yaml:"location"`
	Description  *string                    `json:"description" toml:"description" yaml:"description"`
	URL          *string                    `json:"url" toml:"url" yaml:"url"`
	Slots        *byte                      `json:"slots" toml:"slots" yaml:"slots"`
	MasterServer *string                    `json:"master-server" toml:"master-server" yaml:"master-server"`
	Password     *string                    `json:"password" toml:"password" yaml:"password"`
	TGRewrites   *[]tGRewriteConfigShadow   `json:"tg-rewrite" toml:"tg-rewrite" yaml:"tg-rewrite"`
	PCRewrites   *[]pCRewriteConfigShadow   `json:"pc-rewrite" toml:"pc-rewrite" yaml:"pc-rewrite"`
	TypeRewrites *[]typeRewriteConfigShadow `json:"type-rewrite" toml:"type-rewrite" yaml:"type-rewrite"`
	SrcRewrites  *[]srcRewriteConfigShadow  `json:"src-rewrite" toml:"src-rewrite" yaml:"src-rewrite"`
	PassAllPC    *[]int                     `json:"pass-all-pc" toml:"pass-all-pc" yaml:"pass-all-pc"`
	PassAllTG    *[]int                     `json:"pass-all-tg" toml:"pass-all-tg" yaml:"pass-all-tg"`
}
type iPSCAuthShadow struct {
	Enabled *bool   `json:"enabled" toml:"enabled" yaml:"enabled"`
	Key     *string `json:"key" toml:"key" yaml:"key"`
}
type iPSCShadow struct {
	Interface  *string         `json:"interface" toml:"interface" yaml:"interface"`
	Port       *uint16         `json:"port" toml:"port" yaml:"port"`
	IP         *string         `json:"ip" toml:"ip" yaml:"ip"`
	SubnetMask *int            `json:"subnet-mask" toml:"subnet-mask" yaml:"subnet-mask"`
	Auth       *iPSCAuthShadow `json:"auth" toml:"auth" yaml:"auth"`
}
type configShadow struct {
	LogLevel *string        `json:"log-level" toml:"log-level" yaml:"log-level"`
	Metrics  *metricsShadow `json:"metrics" toml:"metrics" yaml:"metrics"`
	MMDVM    *[]mMDVMShadow `json:"mmdvm" toml:"mmdvm" yaml:"mmdvm"`
	IPSC     *iPSCShadow    `json:"ipsc" toml:"ipsc" yaml:"ipsc"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, sep string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Metrics.Address = ":9100"
	set("metrics.address", configulator.LayerDefault, "default tag")
	cfg.IPSC.IP = "10.10.250.1"
	set("ipsc.ip", configulator.LayerDefault, "default tag")
	cfg.IPSC.SubnetMask = 24
	set("ipsc.subnet-mask", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}
func (s *configShadow) applyTo(cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Metrics != nil {
		if s.Metrics.Enabled != nil {
			cfg.Metrics.Enabled = *s.Metrics.Enabled
			set("metrics.enabled", configulator.LayerFile, file)
		}
		if s.Metrics.Address != nil {
			cfg.Metrics.Address = *s.Metrics.Address
			set("metrics.address", configulator.LayerFile, file)
		}
	}
	if s.MMDVM != nil {
		out := make([]MMDVM, len(*s.MMDVM))
		for i, esh := range *s.MMDVM {
			var e MMDVM
			idx := "mmdvm[" + strconv.Itoa(i) + "]"
			e.Slots = byte(3)
			set(idx+".slots", configulator.LayerDefault, "element default")
			if esh.Name != nil {
				e.Name = *esh.Name
				set(idx+".name", configulator.LayerFile, file)
			}
			if esh.Callsign != nil {
				e.Callsign = *esh.Callsign
				set(idx+".callsign", configulator.LayerFile, file)
			}
			if esh.ID != nil {
				e.ID = *esh.ID
				set(idx+".radio-id", configulator.LayerFile, file)
			}
			if esh.RXFreq != nil {
				e.RXFreq = *esh.RXFreq
				set(idx+".rx-freq", configulator.LayerFile, file)
			}
			if esh.TXFreq != nil {
				e.TXFreq = *esh.TXFreq
				set(idx+".tx-freq", configulator.LayerFile, file)
			}
			if esh.TXPower != nil {
				e.TXPower = *esh.TXPower
				set(idx+".tx-power", configulator.LayerFile, file)
			}
			if esh.ColorCode != nil {
				e.ColorCode = *esh.ColorCode
				set(idx+".color-code", configulator.LayerFile, file)
			}
			if esh.Latitude != nil {
				e.Latitude = *esh.Latitude
				set(idx+".latitude", configulator.LayerFile, file)
			}
			if esh.Longitude != nil {
				e.Longitude = *esh.Longitude
				set(idx+".longitude", configulator.LayerFile, file)
			}
			if esh.Height != nil {
				e.Height = *esh.Height
				set(idx+".height", configulator.LayerFile, file)
			}
			if esh.Location != nil {
				e.Location = *esh.Location
				set(idx+".location", configulator.LayerFile, file)
			}
			if esh.Description != nil {
				e.Description = *esh.Description
				set(idx+".description", configulator.LayerFile, file)
			}
			if esh.URL != nil {
				e.URL = *esh.URL
				set(idx+".url", configulator.LayerFile, file)
			}
			if esh.Slots != nil {
				e.Slots = *esh.Slots
				set(idx+".slots", configulator.LayerFile, file)
			}
			if esh.MasterServer != nil {
				e.MasterServer = *esh.MasterServer
				set(idx+".master-server", configulator.LayerFile, file)
			}
			if esh.Password != nil {
				e.Password = *esh.Password
				set(idx+".password", configulator.LayerFile, file)
			}
			if esh.TGRewrites != nil {
				out1 := make([]TGRewriteConfig, len(*esh.TGRewrites))
				for i1, esh1 := range *esh.TGRewrites {
					var e1 TGRewriteConfig
					idx1 := idx + ".tg-rewrite[" + strconv.Itoa(i1) + "]"
					e1.Range = uint(1)
					set(idx1+".range", configulator.LayerDefault, "element default")
					if esh1.FromSlot != nil {
						e1.FromSlot = *esh1.FromSlot
						set(idx1+".from-slot", configulator.LayerFile, file)
					}
					if esh1.FromTG != nil {
						e1.FromTG = *esh1.FromTG
						set(idx1+".from-tg", configulator.LayerFile, file)
					}
					if esh1.ToSlot != nil {
						e1.ToSlot = *esh1.ToSlot
						set(idx1+".to-slot", configulator.LayerFile, file)
					}
					if esh1.ToTG != nil {
						e1.ToTG = *esh1.ToTG
						set(idx1+".to-tg", configulator.LayerFile, file)
					}
					if esh1.Range != nil {
						e1.Range = *esh1.Range
						set(idx1+".range", configulator.LayerFile, file)
					}
					out1[i1] = e1
				}
				e.TGRewrites = out1
				set(idx+".tg-rewrite", configulator.LayerFile, file)
			}
			if esh.PCRewrites != nil {
				out1 := make([]PCRewriteConfig, len(*esh.PCRewrites))
				for i1, esh1 := range *esh.PCRewrites {
					var e1 PCRewriteConfig
					idx1 := idx + ".pc-rewrite[" + strconv.Itoa(i1) + "]"
					e1.Range = uint(1)
					set(idx1+".range", configulator.LayerDefault, "element default")
					if esh1.FromSlot != nil {
						e1.FromSlot = *esh1.FromSlot
						set(idx1+".from-slot", configulator.LayerFile, file)
					}
					if esh1.FromID != nil {
						e1.FromID = *esh1.FromID
						set(idx1+".from-id", configulator.LayerFile, file)
					}
					if esh1.ToSlot != nil {
						e1.ToSlot = *esh1.ToSlot
						set(idx1+".to-slot", configulator.LayerFile, file)
					}
					if esh1.ToID != nil {
						e1.ToID = *esh1.ToID
						set(idx1+".to-id", configulator.LayerFile, file)
					}
					if esh1.Range != nil {
						e1.Range = *esh1.Range
						set(idx1+".range", configulator.LayerFile, file)
					}
					out1[i1] = e1
				}
				e.PCRewrites = out1
				set(idx+".pc-rewrite", configulator.LayerFile, file)
			}
			if esh.TypeRewrites != nil {
				out1 := make([]TypeRewriteConfig, len(*esh.TypeRewrites))
				for i1, esh1 := range *esh.TypeRewrites {
					var e1 TypeRewriteConfig
					idx1 := idx + ".type-rewrite[" + strconv.Itoa(i1) + "]"
					e1.Range = uint(1)
					set(idx1+".range", configulator.LayerDefault, "element default")
					if esh1.FromSlot != nil {
						e1.FromSlot = *esh1.FromSlot
						set(idx1+".from-slot", configulator.LayerFile, file)
					}
					if esh1.FromTG != nil {
						e1.FromTG = *esh1.FromTG
						set(idx1+".from-tg", configulator.LayerFile, file)
					}
					if esh1.ToSlot != nil {
						e1.ToSlot = *esh1.ToSlot
						set(idx1+".to-slot", configulator.LayerFile, file)
					}
					if esh1.ToID != nil {
						e1.ToID = *esh1.ToID
						set(idx1+".to-id", configulator.LayerFile, file)
					}
					if esh1.Range != nil {
						e1.Range = *esh1.Range
						set(idx1+".range", configulator.LayerFile, file)
					}
					out1[i1] = e1
				}
				e.TypeRewrites = out1
				set(idx+".type-rewrite", configulator.LayerFile, file)
			}
			if esh.SrcRewrites != nil {
				out1 := make([]SrcRewriteConfig, len(*esh.SrcRewrites))
				for i1, esh1 := range *esh.SrcRewrites {
					var e1 SrcRewriteConfig
					idx1 := idx + ".src-rewrite[" + strconv.Itoa(i1) + "]"
					e1.Range = uint(1)
					set(idx1+".range", configulator.LayerDefault, "element default")
					if esh1.FromSlot != nil {
						e1.FromSlot = *esh1.FromSlot
						set(idx1+".from-slot", configulator.LayerFile, file)
					}
					if esh1.FromID != nil {
						e1.FromID = *esh1.FromID
						set(idx1+".from-id", configulator.LayerFile, file)
					}
					if esh1.ToSlot != nil {
						e1.ToSlot = *esh1.ToSlot
						set(idx1+".to-slot", configulator.LayerFile, file)
					}
					if esh1.ToID != nil {
						e1.ToID = *esh1.ToID
						set(idx1+".to-id", configulator.LayerFile, file)
					}
					if esh1.Range != nil {
						e1.Range = *esh1.Range
						set(idx1+".range", configulator.LayerFile, file)
					}
					out1[i1] = e1
				}
				e.SrcRewrites = out1
				set(idx+".src-rewrite", configulator.LayerFile, file)
			}
			if esh.PassAllPC != nil {
				e.PassAllPC = *esh.PassAllPC
				set(idx+".pass-all-pc", configulator.LayerFile, file)
			}
			if esh.PassAllTG != nil {
				e.PassAllTG = *esh.PassAllTG
				set(idx+".pass-all-tg", configulator.LayerFile, file)
			}
			out[i] = e
		}
		cfg.MMDVM = out
		set("mmdvm", configulator.LayerFile, file)
	}
	if s.IPSC != nil {
		if s.IPSC.Interface != nil {
			cfg.IPSC.Interface = *s.IPSC.Interface
			set("ipsc.interface", configulator.LayerFile, file)
		}
		if s.IPSC.Port != nil {
			cfg.IPSC.Port = *s.IPSC.Port
			set("ipsc.port", configulator.LayerFile, file)
		}
		if s.IPSC.IP != nil {
			cfg.IPSC.IP = *s.IPSC.IP
			set("ipsc.ip", configulator.LayerFile, file)
		}
		if s.IPSC.SubnetMask != nil {
			cfg.IPSC.SubnetMask = *s.IPSC.SubnetMask
			set("ipsc.subnet-mask", configulator.LayerFile, file)
		}
		if s.IPSC.Auth != nil {
			if s.IPSC.Auth.Enabled != nil {
				cfg.IPSC.Auth.Enabled = *s.IPSC.Auth.Enabled
				set("ipsc.auth.enabled", configulator.LayerFile, file)
			}
			if s.IPSC.Auth.Key != nil {
				cfg.IPSC.Auth.Key = *s.IPSC.Auth.Key
				set("ipsc.auth.key", configulator.LayerFile, file)
			}
		}
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "log-level"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.LogLevel = LogLevel(v)
			set("log-level", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "metrics.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.Metrics.Enabled = p
			set("metrics.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "metrics", "address"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Metrics.Address = v
			set("metrics.address", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "ipsc", "interface"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.IPSC.Interface = v
			set("ipsc.interface", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "ipsc", "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseUint(v, 10, 16)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "ipsc.port",
					Source: n,
					Value:  v,
				}
			}
			cfg.IPSC.Port = uint16(p)
			set("ipsc.port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "ipsc", "ip"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.IPSC.IP = v
			set("ipsc.ip", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "ipsc", "subnet-mask"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "ipsc.subnet-mask",
					Source: n,
					Value:  v,
				}
			}
			cfg.IPSC.SubnetMask = int(p)
			set("ipsc.subnet-mask", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "ipsc", "auth", "enabled"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseBool(v)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "ipsc.auth.enabled",
					Source: n,
					Value:  v,
				}
			}
			cfg.IPSC.Auth.Enabled = p
			set("ipsc.auth.enabled", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "ipsc", "auth", "key"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.IPSC.Auth.Key = v
			set("ipsc.auth.key", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}
func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{strings.Join([]string{"log-level"}, o.Separator), strings.Join([]string{"metrics", "enabled"}, o.Separator), strings.Join([]string{"metrics", "address"}, o.Separator), strings.Join([]string{"ipsc", "interface"}, o.Separator), strings.Join([]string{"ipsc", "port"}, o.Separator), strings.Join([]string{"ipsc", "ip"}, o.Separator), strings.Join([]string{"ipsc", "subnet-mask"}, o.Separator), strings.Join([]string{"ipsc", "auth", "enabled"}, o.Separator), strings.Join([]string{"ipsc", "auth", "key"}, o.Separator)}
	for i, name := range names {
		if fs.Lookup(name) != nil || slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.Bool(names[1], false, "Whether to enable Prometheus metrics endpoint")
	fs.String(names[2], ":9100", "Address to serve Prometheus metrics on")
	fs.String(names[3], "", "Interface to listen for IPSC packets on")
	fs.Uint16(names[4], uint16(0), "Port to listen for IPSC packets on")
	fs.String(names[5], "10.10.250.1", "IP address to listen for IPSC packets on")
	fs.Int(names[6], 24, "Subnet mask for the virtual network interface created for IPSC packets")
	fs.Bool(names[7], false, "Whether to require authentication for IPSC clients")
	fs.String(names[8], "", "Authentication key for IPSC clients. Required if auth is enabled")
	return nil
}
func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, sep string, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"log-level"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.enabled",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Enabled = v
		set("metrics.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"metrics", "address"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "metrics.address",
				Source: "--" + n,
			}
		}
		cfg.Metrics.Address = v
		set("metrics.address", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"ipsc", "interface"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ipsc.interface",
				Source: "--" + n,
			}
		}
		cfg.IPSC.Interface = v
		set("ipsc.interface", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"ipsc", "port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetUint16(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ipsc.port",
				Source: "--" + n,
			}
		}
		cfg.IPSC.Port = v
		set("ipsc.port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"ipsc", "ip"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ipsc.ip",
				Source: "--" + n,
			}
		}
		cfg.IPSC.IP = v
		set("ipsc.ip", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"ipsc", "subnet-mask"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ipsc.subnet-mask",
				Source: "--" + n,
			}
		}
		cfg.IPSC.SubnetMask = v
		set("ipsc.subnet-mask", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"ipsc", "auth", "enabled"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetBool(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ipsc.auth.enabled",
				Source: "--" + n,
			}
		}
		cfg.IPSC.Auth.Enabled = v
		set("ipsc.auth.enabled", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"ipsc", "auth", "key"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "ipsc.auth.key",
				Source: "--" + n,
			}
		}
		cfg.IPSC.Auth.Key = v
		set("ipsc.auth.key", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.LogLevel = &str
			default:
				return fmt.Errorf("log-level: expected a string, got %v", v.Kind())
			}
		case "metrics":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub metricsShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Metrics = &sub
			}
		case "mmdvm":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("mmdvm: expected an array, got %v", tok.Kind())
				}
				out := []mMDVMShadow{}
				for dec.PeekKind() != ']' {
					var el mMDVMShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.MMDVM = &out
			}
		case "ipsc":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub iPSCShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.IPSC = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

func (s *metricsShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		case "address":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Address = &str
			default:
				return fmt.Errorf("address: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*metricsShadow)(nil)

func (s *mMDVMShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "name":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Name = &str
			default:
				return fmt.Errorf("name: expected a string, got %v", v.Kind())
			}
		case "callsign":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Callsign = &str
			default:
				return fmt.Errorf("callsign: expected a string, got %v", v.Kind())
			}
		case "radio-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint32 {
					return fmt.Errorf("radio-id: %d overflows uint32", num)
				}
				val := uint32(num)
				s.ID = &val
			default:
				return fmt.Errorf("radio-id: expected a number, got %v", v.Kind())
			}
		case "rx-freq":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.RXFreq = &val
			default:
				return fmt.Errorf("rx-freq: expected a number, got %v", v.Kind())
			}
		case "tx-freq":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.TXFreq = &val
			default:
				return fmt.Errorf("tx-freq: expected a number, got %v", v.Kind())
			}
		case "tx-power":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint8 {
					return fmt.Errorf("tx-power: %d overflows uint8", num)
				}
				val := uint8(num)
				s.TXPower = &val
			default:
				return fmt.Errorf("tx-power: expected a number, got %v", v.Kind())
			}
		case "color-code":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint8 {
					return fmt.Errorf("color-code: %d overflows uint8", num)
				}
				val := uint8(num)
				s.ColorCode = &val
			default:
				return fmt.Errorf("color-code: expected a number, got %v", v.Kind())
			}
		case "latitude":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.Latitude = &val
			default:
				return fmt.Errorf("latitude: expected a number, got %v", v.Kind())
			}
		case "longitude":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.Longitude = &val
			default:
				return fmt.Errorf("longitude: expected a number, got %v", v.Kind())
			}
		case "height":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("height: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Height = &val
			default:
				return fmt.Errorf("height: expected a number, got %v", v.Kind())
			}
		case "location":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Location = &str
			default:
				return fmt.Errorf("location: expected a string, got %v", v.Kind())
			}
		case "description":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Description = &str
			default:
				return fmt.Errorf("description: expected a string, got %v", v.Kind())
			}
		case "url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.URL = &str
			default:
				return fmt.Errorf("url: expected a string, got %v", v.Kind())
			}
		case "slots":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint8 {
					return fmt.Errorf("slots: %d overflows byte", num)
				}
				val := byte(num)
				s.Slots = &val
			default:
				return fmt.Errorf("slots: expected a number, got %v", v.Kind())
			}
		case "master-server":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.MasterServer = &str
			default:
				return fmt.Errorf("master-server: expected a string, got %v", v.Kind())
			}
		case "password":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Password = &str
			default:
				return fmt.Errorf("password: expected a string, got %v", v.Kind())
			}
		case "tg-rewrite":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("tg-rewrite: expected an array, got %v", tok.Kind())
				}
				out := []tGRewriteConfigShadow{}
				for dec.PeekKind() != ']' {
					var el tGRewriteConfigShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TGRewrites = &out
			}
		case "pc-rewrite":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("pc-rewrite: expected an array, got %v", tok.Kind())
				}
				out := []pCRewriteConfigShadow{}
				for dec.PeekKind() != ']' {
					var el pCRewriteConfigShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.PCRewrites = &out
			}
		case "type-rewrite":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("type-rewrite: expected an array, got %v", tok.Kind())
				}
				out := []typeRewriteConfigShadow{}
				for dec.PeekKind() != ']' {
					var el typeRewriteConfigShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.TypeRewrites = &out
			}
		case "src-rewrite":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("src-rewrite: expected an array, got %v", tok.Kind())
				}
				out := []srcRewriteConfigShadow{}
				for dec.PeekKind() != ']' {
					var el srcRewriteConfigShadow
					if err := el.UnmarshalJSONFrom(dec); err != nil {
						return err
					}
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.SrcRewrites = &out
			}
		case "pass-all-pc":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("pass-all-pc: expected an array, got %v", tok.Kind())
				}
				out := []int{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '0' {
						return fmt.Errorf("pass-all-pc: expected a number element, got %v", v.Kind())
					}
					raw, err := v.Int()
					if err != nil {
						return err
					}
					el := int(raw)
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.PassAllPC = &out
			}
		case "pass-all-tg":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("pass-all-tg: expected an array, got %v", tok.Kind())
				}
				out := []int{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '0' {
						return fmt.Errorf("pass-all-tg: expected a number element, got %v", v.Kind())
					}
					raw, err := v.Int()
					if err != nil {
						return err
					}
					el := int(raw)
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.PassAllTG = &out
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*mMDVMShadow)(nil)

func (s *tGRewriteConfigShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "from-slot":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.FromSlot = &val
			default:
				return fmt.Errorf("from-slot: expected a number, got %v", v.Kind())
			}
		case "from-tg":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.FromTG = &val
			default:
				return fmt.Errorf("from-tg: expected a number, got %v", v.Kind())
			}
		case "to-slot":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.ToSlot = &val
			default:
				return fmt.Errorf("to-slot: expected a number, got %v", v.Kind())
			}
		case "to-tg":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.ToTG = &val
			default:
				return fmt.Errorf("to-tg: expected a number, got %v", v.Kind())
			}
		case "range":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.Range = &val
			default:
				return fmt.Errorf("range: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*tGRewriteConfigShadow)(nil)

func (s *pCRewriteConfigShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "from-slot":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.FromSlot = &val
			default:
				return fmt.Errorf("from-slot: expected a number, got %v", v.Kind())
			}
		case "from-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.FromID = &val
			default:
				return fmt.Errorf("from-id: expected a number, got %v", v.Kind())
			}
		case "to-slot":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.ToSlot = &val
			default:
				return fmt.Errorf("to-slot: expected a number, got %v", v.Kind())
			}
		case "to-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.ToID = &val
			default:
				return fmt.Errorf("to-id: expected a number, got %v", v.Kind())
			}
		case "range":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.Range = &val
			default:
				return fmt.Errorf("range: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*pCRewriteConfigShadow)(nil)

func (s *typeRewriteConfigShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "from-slot":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.FromSlot = &val
			default:
				return fmt.Errorf("from-slot: expected a number, got %v", v.Kind())
			}
		case "from-tg":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.FromTG = &val
			default:
				return fmt.Errorf("from-tg: expected a number, got %v", v.Kind())
			}
		case "to-slot":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.ToSlot = &val
			default:
				return fmt.Errorf("to-slot: expected a number, got %v", v.Kind())
			}
		case "to-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.ToID = &val
			default:
				return fmt.Errorf("to-id: expected a number, got %v", v.Kind())
			}
		case "range":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.Range = &val
			default:
				return fmt.Errorf("range: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*typeRewriteConfigShadow)(nil)

func (s *srcRewriteConfigShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "from-slot":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.FromSlot = &val
			default:
				return fmt.Errorf("from-slot: expected a number, got %v", v.Kind())
			}
		case "from-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.FromID = &val
			default:
				return fmt.Errorf("from-id: expected a number, got %v", v.Kind())
			}
		case "to-slot":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.ToSlot = &val
			default:
				return fmt.Errorf("to-slot: expected a number, got %v", v.Kind())
			}
		case "to-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.ToID = &val
			default:
				return fmt.Errorf("to-id: expected a number, got %v", v.Kind())
			}
		case "range":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				val := uint(num)
				s.Range = &val
			default:
				return fmt.Errorf("range: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*srcRewriteConfigShadow)(nil)

func (s *iPSCShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "interface":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Interface = &str
			default:
				return fmt.Errorf("interface: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Uint()
				if err != nil {
					return err
				}
				if num > math.MaxUint16 {
					return fmt.Errorf("port: %d overflows uint16", num)
				}
				val := uint16(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "ip":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.IP = &str
			default:
				return fmt.Errorf("ip: expected a string, got %v", v.Kind())
			}
		case "subnet-mask":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.SubnetMask = &val
			default:
				return fmt.Errorf("subnet-mask: expected a number, got %v", v.Kind())
			}
		case "auth":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub iPSCAuthShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Auth = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*iPSCShadow)(nil)

func (s *iPSCAuthShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "enabled":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case 't', 'f':
				b := v.Bool()
				s.Enabled = &b
			default:
				return fmt.Errorf("enabled: expected a bool, got %v", v.Kind())
			}
		case "key":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Key = &str
			default:
				return fmt.Errorf("key: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*iPSCAuthShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("log-level = %v\n", c.LogLevel))
	b.WriteString(fmt.Sprintf("metrics.enabled = %v\n", c.Metrics.Enabled))
	b.WriteString(fmt.Sprintf("metrics.address = %v\n", c.Metrics.Address))
	b.WriteString("mmdvm = (redacted)\n")
	b.WriteString(fmt.Sprintf("ipsc.interface = %v\n", c.IPSC.Interface))
	b.WriteString(fmt.Sprintf("ipsc.port = %v\n", c.IPSC.Port))
	b.WriteString(fmt.Sprintf("ipsc.ip = %v\n", c.IPSC.IP))
	b.WriteString(fmt.Sprintf("ipsc.subnet-mask = %v\n", c.IPSC.SubnetMask))
	b.WriteString(fmt.Sprintf("ipsc.auth.enabled = %v\n", c.IPSC.Auth.Enabled))
	b.WriteString("ipsc.auth.key = (redacted)\n")
	return b.String()
}
